[versions]
agp = "8.2.0"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
activityCompose = "1.9.0"
appcompat = "1.6.1"
constraintLayout = "2.1.4"
coreKtx = "1.13.0"
espresso = "3.5.1"
material = "1.11.0"
androidxJunit = "1.1.5"
compose = "1.6.8"
composePlugin = "1.6.2"
junit = "4.13.2"
kotlin = "1.9.23"
ksp = "1.9.23-1.0.19"

lifecycleViewModel = "2.8.3"
koin = "3.6.0-Beta5"
koinCompose = "1.2.0-alpha3"
koinComposeViewModel = "1.2.0-Beta4"
navigationCompose = "2.7.0-alpha03"
room = "2.7.0-alpha05"
sqlite = "2.5.0-alpha05"
kotlinxDateTime = "0.5.0"
turbine = "1.1.0"
coroutines = "1.8.1"
mockk = "1.13.12"


[libraries]


# Kotlix DateTime
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime"}

# Lifecycle
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewModel"}
lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleViewModel" }

# Coroutines
kotlinx-coroutines = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref="coroutines"}

#Room
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

# Koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinCompose" }
koin-compose-viewmodel = {module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koinComposeViewModel"}

# Compose
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

#Testing
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin"}
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines"}
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine"}
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin"}
mockk = { module = "io.mockk:mockk", version.ref = "mockk"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "composePlugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidxRoom = { id = "androidx.room", version.ref = "room" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }