name: Publish to Play Store

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew


    - name: Create local.properties
      env:
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
        GOOGLE_AUTH_CLIENT_ID_SERVER: ${{ secrets.GOOGLE_AUTH_CLIENT_ID_SERVER }}
        GOOGLE_AUTH_CLIENT_ID_DESKTOP: ${{ secrets.GOOGLE_AUTH_CLIENT_ID_DESKTOP }}
        GOOGLE_AUTH_CLIENT_SECRET_DESKTOP: ${{ secrets.GOOGLE_AUTH_CLIENT_SECRET_DESKTOP }}
      run: |
        echo "API_BASE_URL=$API_BASE_URL" > local.properties
        echo "API_KEY=$API_KEY" >> local.properties
        echo "GOOGLE_AUTH_CLIENT_ID_SERVER=$GOOGLE_AUTH_CLIENT_ID_SERVER" >> local.properties
        echo "GOOGLE_AUTH_CLIENT_ID_DESKTOP=$GOOGLE_AUTH_CLIENT_ID_DESKTOP" >> local.properties
        echo "GOOGLE_AUTH_CLIENT_SECRET_DESKTOP=$GOOGLE_AUTH_CLIENT_SECRET_DESKTOP" >> local.properties
        

    - name: Restore google-services.js
      env:
        GS_JSON_BASE64: ${{ secrets.GS_JSON_BASE64 }}
      run: |
        echo "$GS_JSON_BASE64" | base64 --decode > google-services.json
        mv google-services.json composeApp/google-services.json 

    - name: Version Bump
      uses: chkfung/android-version-actions@v1.2.3
      with:
        gradlePath: composeApp/build.gradle.kts
        versionCode: ${{ github.run_number }}

    - name: Build Release Bundle
      run: ./gradlew :composeApp:bundleRelease

    - name: Sign Release
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: composeApp/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: Upload to Play Store
      uses: r0adkll/upload-google-play@v1.1.3
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY }}
        packageName: br.com.noartcode.theprice
        releaseFiles: composeApp/build/outputs/bundle/release/composeApp-release.aab
        track: internal
        status: draft

    - name: Delete local.properties
      if: always()
      run: rm -f local.properties